lib/python/cpxview.py   BUGFIX: using /usr/bin/env python instead of /usr/bin/python now. scr/adore   BUGFIX: Checks the usual canonicalpath if LSOF is not available. scr/fun/quejob   BUGFIX: No need to specify the quename. Just submit to default. Also pass PATH variable as a precaution scr/fun/plotting.fun   BUGFIX: Added error control on the minmax functions. If they fail return. scr/fun/waitjob   HELP: Corrected the wrong help message. scr/fun/dem   BUGFIX: Does not rely on the i_resfile anymore. Resfile is created if not found. scr/fun/functions   BUGFIX: addrefpha2crop renamed to addrefpha2s_crop scr/deprecated/deprecated.fun   ADD: added a functions table for deprecated functions. Need to figure out how to display deprecated message. scr/process/m_porbits   BUGFIX: if m_orbdir is not present. Does not run DORIS. Doris waits if batchmode is off. templates/multiplePairs_resampled_parallel.adr   ADD: New ADORE script for SBAS style interferograms. Not tested. Demeter has issues with Torque-PBS templates/baselines.adr   BUGFIX: Now calculates m_readfiles and m_porbits instead of s_* templates/multiplePairs_resampled.adr   Small adjustments in the commands for resample and interfero.

diff --git a/trunk/scr/adore b/trunk/scr/adore
--- a/trunk/scr/adore
+++ b/trunk/scr/adore
@@ -80,9 +80,21 @@ export adoreCommand=$1
 export dorisProcess=$p
 
 if [ "${ADORESCR:-isEmpty}" = "isEmpty" ]; then
+  #Two methods to find ADORE path 
+  #LSOF is capable of following links. But not available on all systems
+  #dirname method can not follow links causing trouble when adore is a link. 
   LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$") # get the location of running script
-  [ $? -ne 0 ] && echo "ADORE could not define ADORESCR. Please set it as environment variable and retry. ex: export ADORESCR=/opt/adore/scr" && exit
-  export ADORESCR=$(dirname ${LSOF##* })
+  if [ $? -ne 0 ]; then 
+   ADORESCR=`echo $(cd $(dirname ${0}); pwd -P)`
+   if [ -d ${ADORESCR}/fun ]; then 
+     export ADORESCR
+   else
+     echo "ADORE could not define ADORESCR. Please set it as environment variable and retry. ex: export ADORESCR=/opt/adore/scr"
+     exit
+   fi
+  else
+    export ADORESCR=$(dirname ${LSOF##* })
+  fi
 fi
 echo ADORESCR=${ADORESCR}
 #adjust path in /ADORESCR/.adore.rc, only if interactive
