scr/.adore.rc:   FEAT: Added a new function to check the folder of the settings file and the PWD.   If different the ADORE prompt changes to !ADORE: to indicate that the settings   file is not in the current folder. This is especially useful, when multiple   interferograms are processed with ADORE scripts. scr/fun/tabcompletion   BUGFIX: Fixed missing options for the scenes command. scr/fun/undo   BUGFIX: Fixed unnecessary warning messages when result files do not exist. Useful   in crops where the slave and interfero result files point to "dummy" scr/fun/functions   FEAT: Added new function called "setPS1". This function checks the "dirname $u" and $PWD.   When equal prompt is set to ADORE: else set to !ADORE:

diff --git a/trunk/scr/fun/undo b/trunk/scr/fun/undo
--- a/trunk/scr/fun/undo
+++ b/trunk/scr/fun/undo
@@ -40,21 +40,26 @@ dorisProcessReset()
 ## reset doris steps in the result files,
 ## up to the processing step you want
 ##
+
+ if [ -e "${2}" ]; then
     
- lineno=$(awk '/_Start_'$1'/{print NR-1}' $2);  # get me the line number of the process line - 1
- 
- if [ "$lineno" != "" ]; then 
-   echo "  ${1} found at ${lineno} in ${2}"
-   if [ "${3}" == "only" ]; then
-     linenoEnd=$(awk '/End_'$1'/{print NR+1}' $2);  #get the line number for the end of step.
-     sed -i -e '/^'$1'/s/1/0/g' -e ''${lineno},${linenoEnd}' d' $2
-     [ $? -eq 0 ] && echo "  Undo Successful."
+   lineno=$(awk '/_Start_'$1'/{print NR-1}' $2);  # get me the line number of the process line - 1
+    
+   if [ "$lineno" != "" ]; then 
+     echo "  ${1} found at ${lineno} in ${2}"
+     if [ "${3}" == "only" ]; then
+       linenoEnd=$(awk '/End_'$1'/{print NR+1}' $2);  #get the line number for the end of step.
+       sed -i -e '/^'$1'/s/1/0/g' -e ''${lineno},${linenoEnd}' d' $2
+       [ $? -eq 0 ] && echo "  Undo Successful."
+     else
+       sed -i -e '/^'$1'/,/End_process_control/s/1/0/g' -e ''${lineno}',$ d' $2
+       [ $? -eq 0 ] && echo "  Undo Successful."
+     fi
    else
-     sed -i -e '/^'$1'/,/End_process_control/s/1/0/g' -e ''${lineno}',$ d' $2
-     [ $? -eq 0 ] && echo "  Undo Successful."
+     echo "  ${1} not found in ${2}. This might not be important."
    fi
  else
-   echo "  ${1} not found in ${2}. This might not be important."
+   echo "  ${2} does not exist. This might not be important."
  fi
 }
 
