trunk/man/bin/wiki2txt.sh   BUGFIX: Added space at the end of each file trunk/man/txt/*   Updated the files from online wiki trunk/set/resolution.csv   FEAT: Added SAR resolution database. We set slc_*_res during scenes init trunk/templates/baselines.adr   BUGFIX: If the baselines folder already exists, remove and re-do trunk/lib/python/cpxoffset.py, trunk/lib/python/cpxview.py   BUGFIX: added -r auto option which scales the image based on 3 sigma trunk/lib/python/deramp.py   FEAT: Added FFT based phase-deramping for complex imagery. trunk/lib/python/giant/prepxml_SBAS.py   FEAT: Now we support dem and dem_correction in giant. trunk/scr/rs2pn   BUGFIX: The longname for ci2 was wrong. trunk/scr/fun/superMasterResample   BUGFIX: Now we remove topographic signal in the resample step as well.   I noticed some weird issued with ALOS and decided that it is probably best   to remove the same topography(height) from all imagery. Of course the bperp   is scaled correctly... trunk/scr/fun/dem   FEAT: Added dem export function. Used for GIANT. Also renamed convert to import. trunk/scr/fun/addrefpha2s_crop   BUGFIX/FEAT: If crd is available and not srprefpha than subtracts crd. It is   important to have crd with crd_include_fe=on trunk/scr/fun/report   FEAT: Added javascript to show/hide results trunk/scr/fun/check   FEAT: Now the -p option accepts an optional filename trunk/scr/fun/i12s   FEAT: Added i12s plot function to display a temporal perpendicular network plot trunk/scr/fun/scenes   FEAT: Added the setSlcRes function for setting slc_*_res during scenes init. trunk/scr/process/coarsecorr   BUGFIX: Added the -r auto flag to increase the dynamic range.

diff --git a/scr/fun/addrefpha2s_crop b/scr/fun/addrefpha2s_crop
--- a/scr/fun/addrefpha2s_crop
+++ b/scr/fun/addrefpha2s_crop
@@ -20,12 +20,26 @@
 
 function funResample2Tmpfile(){
   tmpFile=${1}
-  [ ! -e "${rs_out_file}" ] && error "Resample file not found. Please run resample step" && return 1
-  [ ! -e "${srp_out_refpha}" ] && error "Reference phase file not found. Please run subtrrefpha with dumprefpha=on" && return 1
-
-  bold "Adding reference phase to resampled slave..."
-  cpxmult ${rs_out_file} ${srp_out_refpha} ${rs_out_file}.addrefpha 1
-  [ $? -ne 0 ] && error "cpxmult can not multiply." && return 1
+  [ ! -e "${rs_out_file}" ] && error "Resample file not found. Please run resample step" && return 
+  #[ ! -e "${srp_out_refpha}" ] && error "Reference phase file not found. Please run subtrrefpha with dumprefpha=on" && return 
+  if [ ! -e "${srp_out_refpha}" ] && [ ! -e "${crd_out_file}" ] ; then
+    error "Reference phase file not found. Please run subtrrefpha with dumprefpha=on or comprefdem with crd_include_fe=on"
+    return 
+  fi
+  
+  if [ -e "${crd_out_file}" ]; then 
+    bold "Adding reference phase and topographic phase to resampled slave..."
+    local fileName resFile format width numlines
+    call "(fileName resFile format width numlines)=dorisProcess2OutputFile comprefdem"
+    ${ADOREFOLDER}/lib/python/real2cpx.py -w ${width} -f ${format} -m 1 -p ${crd_out_file} ${crd_out_file}.cpx
+    [ $? -ne 0 ] && error "real2cpx failed." && return 1
+    cpxmult ${rs_out_file} ${crd_out_file}.cpx ${rs_out_file}.addrefpha 1
+    [ $? -ne 0 ] && error "cpxmult can not multiply." && return 1
+  else
+    bold "Adding reference phase to resampled slave..."
+    cpxmult ${rs_out_file} ${srp_out_refpha} ${rs_out_file}.addrefpha 1
+    [ $? -ne 0 ] && error "cpxmult can not multiply." && return 1
+  fi    
   cp ${s_resfile} ${s_resfile}.bck
 
   # Below line copies the information from the requested step and copies it to a temporary file
@@ -66,7 +80,8 @@ function funResample2Crop(){
   funResample2Tmpfile ${tmpFile}
   [ $? -ne 0 ] && return 1 
   
-  undo crop ${s_resfile}
+  undo only crop ${s_resfile}
+  undo only resample ${s_resfile}
 
   # Re-write crop for resampling.
   sed -i -e '/^crop/s/0/1/g' ${s_resfile}
@@ -86,7 +101,8 @@ function funResample2Ovs(){
   funResample2Tmpfile ${tmpFile}
   [ $? -ne 0 ] && return 1 
   
-  undo oversample ${s_resfile}
+  undo only oversample ${s_resfile}
+  undo only resample ${s_resfile}
 
   # Re-write crop for resampling.
   sed -i -e '/^oversample/s/0/1/g' ${s_resfile}
