lib/python/cpxview.py   FEAT: added support for -M option scr/adore   BUGFIX: now unsets ${i} after starting bash. Otherwise all spawned ADORE jobs (parallel processing) run in interactive mode. scr/fun/quejob   Minor corrections. Removed exporting path. Not necessary. Now error messages are sent to stderr. scr/fun/raster   Added auto option for a,p,m. tries to guess between a and p scr/fun/report   Added text support. Fixed the problem with alternate interferograms folder.

diff --git a/scr/fun/quejob b/scr/fun/quejob
--- a/scr/fun/quejob
+++ b/scr/fun/quejob
@@ -20,7 +20,7 @@
 
 function createJob(){
 local qsubPath=`which qsub`
-[ "${qsubPath:-IsEmpty}" == "IsEmpty" ] && echo "Torque PBS, qsub, not found." && return 110
+[ "${qsubPath:-IsEmpty}" == "IsEmpty" ] && echo "Torque PBS, qsub, not found." >&2 && return 110
 
 local commands=${1};
 local CALLDIR qsubOpts
@@ -34,7 +34,7 @@ elif [ "${2}" == "--" ]; then
   CALLDIR="${PWD}";  
   qsubOpts="${@:3}"
 else
-  echo "Wrong parameter. Please check usage with: ? quejob"
+  echo "Wrong parameter. Please check usage with: ? quejob" >&2
 fi
 
 generateRandomString 
