trunk/lib/python/adore.py   FEAT: Added drs2dict (and input2dict) functions to read drs files. Also added support for reading 'cr2' half-precision float files (tandem-x) correctly. trunk/scr/modifyRes.sh   BUGFIX/FEAT: Changed the way lines are updated so that now modifyRes is applied directly to the file (via sed -i). trunk/scr/fun/saveas   BUGFIX: Removed the -N32767 flag for grd format. The default option NaN works better. Also added the grdreformat line back to grd format. This way the grd files can be opened with GDAL/QGIS. trunk/scr/fun/s_crop2resample   BUGFIX: Added support for correctly copying the ci2 format crops as resample. This is required for multiple_pair resampled processing. trunk/scr/fun/addrefpha2s_crop   BUGFIX/FEAT: Added a check for failed cpxmult statement. If happens no change is applied. trunk/scr/fun/functions   BUGFIX/FEAT: Updated the way the cc_winsize is set. If small it is 5x5, large size = srp_mutlilook*int_multilook. if middle=2*srp_mutlilook*int_multilook trunk/scr/fun/report   BUGFIX: updated the way the image size is calculated. Now it sets the sizes properly (proportional to interferogram size).

diff --git a/scr/fun/saveas b/scr/fun/saveas
--- a/scr/fun/saveas
+++ b/scr/fun/saveas
@@ -363,12 +363,12 @@ function saveas_grd(){
     region=`minmax -I${slc_res_deg} -bis3 ${outName}.dat` 
     [ $? -ne 0 ] && echo "Error running command: minmax -I${slc_res_deg} -bis3 ${outName}.dat" && return 1
     #generate grd file
-    xyz2grd ${outName}.dat -bis3 -G${outName}.grd ${region} -I${slc_res_deg} -N32767 -V
-    #change grid to the older format (gdal complienat)
-    #grdreformat ${outName}.grd ${outName}_grdreformat.grd=sf -V || { echo "Error running command: $_"; return 1; }
+    xyz2grd ${outName}.dat -bis3 -G${outName}_default.grd ${region} -I${slc_res_deg} -V || { echo "Error running command: $_"; return 1; } #-N32767 
+    #change grid to the older format (gdal compliant)
+    grdreformat ${outName}_default.grd ${outName}.grd=sf -V || { echo "Error running command: $_"; return 1; }
     if [ $? -ne 0 ]; then
-      echo "xyz2grd failed. I was trying to run: xyz2grd ${outName}.dat -bis3 -G${outName}.grd ${region} -I${slc_res_deg} -N32767 -V";
-      echo "I might have left behind temporary files: ${outName}.temporary ${outName}.dat"
+      echo "saveas_grd failed."
+      echo "I might have left behind temporary files: ${outName}.temporary ${outName}.dat ${outName}_default.grd"
       return
     else
       #cleanup
